// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotAdmin) DeepCopyInto(out *PilotAdmin) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotAdmin.
func (in *PilotAdmin) DeepCopy() *PilotAdmin {
	if in == nil {
		return nil
	}
	out := new(PilotAdmin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PilotAdmin) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotAdminList) DeepCopyInto(out *PilotAdminList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PilotAdmin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotAdminList.
func (in *PilotAdminList) DeepCopy() *PilotAdminList {
	if in == nil {
		return nil
	}
	out := new(PilotAdminList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PilotAdminList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotAdminSpec) DeepCopyInto(out *PilotAdminSpec) {
	*out = *in
	if in.PilotSelector != nil {
		in, out := &in.PilotSelector, &out.PilotSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Limit != nil {
		in, out := &in.Limit, &out.Limit
		*out = new(PilotAdminSpec_Limit)
		(*in).DeepCopyInto(*out)
	}
	if in.Loadbalance != nil {
		in, out := &in.Loadbalance, &out.Loadbalance
		*out = new(PilotAdminSpec_LoadBalance)
		(*in).DeepCopyInto(*out)
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotAdminSpec.
func (in *PilotAdminSpec) DeepCopy() *PilotAdminSpec {
	if in == nil {
		return nil
	}
	out := new(PilotAdminSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotAdminSpec_Limit) DeepCopyInto(out *PilotAdminSpec_Limit) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotAdminSpec_Limit.
func (in *PilotAdminSpec_Limit) DeepCopy() *PilotAdminSpec_Limit {
	if in == nil {
		return nil
	}
	out := new(PilotAdminSpec_Limit)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotAdminSpec_LoadBalance) DeepCopyInto(out *PilotAdminSpec_LoadBalance) {
	*out = *in
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotAdminSpec_LoadBalance.
func (in *PilotAdminSpec_LoadBalance) DeepCopy() *PilotAdminSpec_LoadBalance {
	if in == nil {
		return nil
	}
	out := new(PilotAdminSpec_LoadBalance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotAdminStatus) DeepCopyInto(out *PilotAdminStatus) {
	*out = *in
	if in.Endpoints != nil {
		in, out := &in.Endpoints, &out.Endpoints
		*out = make(map[string]*PilotAdminStatus_EndpointStatus, len(*in))
		for key, val := range *in {
			var outVal *PilotAdminStatus_EndpointStatus
			if val == nil {
				(*out)[key] = nil
			} else {
				in, out := &val, &outVal
				*out = new(PilotAdminStatus_EndpointStatus)
				(*in).DeepCopyInto(*out)
			}
			(*out)[key] = outVal
		}
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotAdminStatus.
func (in *PilotAdminStatus) DeepCopy() *PilotAdminStatus {
	if in == nil {
		return nil
	}
	out := new(PilotAdminStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PilotAdminStatus_EndpointStatus) DeepCopyInto(out *PilotAdminStatus_EndpointStatus) {
	*out = *in
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.XXX_NoUnkeyedLiteral = in.XXX_NoUnkeyedLiteral
	if in.XXX_unrecognized != nil {
		in, out := &in.XXX_unrecognized, &out.XXX_unrecognized
		*out = make([]byte, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PilotAdminStatus_EndpointStatus.
func (in *PilotAdminStatus_EndpointStatus) DeepCopy() *PilotAdminStatus_EndpointStatus {
	if in == nil {
		return nil
	}
	out := new(PilotAdminStatus_EndpointStatus)
	in.DeepCopyInto(out)
	return out
}
