apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pilotadmins.microservice.slime.io
spec:
  group: microservice.slime.io
  names:
    shortNames:
      - pa
    kind: PilotAdmin
    listKind: PilotAdminList
    plural: pilotadmins
    singular: pilotadmin
  scope: Namespaced
  subresources:
    status: { }
  versions:
    - name: v1alpha1
      served: true
      storage: true
